const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');

test('Arşiv araması, sayaçlar, ders birleştirme ve moderasyon migrationı', async t => {
    const { PGlite } = await import('@electric-sql/pglite');
    const db = new PGlite();
    const owner = '11111111-1111-4111-8111-111111111111';
    const reporter = '22222222-2222-4222-8222-222222222222';
    const q1 = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
    const q2 = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
    try {
        await db.exec(`
            create role anon; create role authenticated;
            create schema auth;
            create table auth.users(id uuid primary key,email text);
            create function auth.uid() returns uuid language sql stable as
                $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
            create table public.fakulteler(id integer primary key,ad text not null);
            create table public.bolumler(id integer primary key,ad text not null,fakulte_id integer references public.fakulteler);
            create table public.nk_dersler(id integer generated by default as identity primary key,bolum_id integer references public.bolumler,
                ders_adi text not null,ders_kodu text,ekleyen_kullanici_id uuid references auth.users,
                olusturulma_tarihi timestamptz not null default now());
            create table public.sorular(id uuid primary key default gen_random_uuid(),ders_id integer references public.nk_dersler,
                kullanici_id uuid references auth.users,sinav_turu text,akademik_yil integer,element_yollari text[],
                durum text not null default 'beklemede',olusturulma_tarihi timestamptz not null default now());
            create function public._admin_token_gecerli_mi(t text) returns boolean language sql as $$ select t='test-admin' $$;
            create function public.nk_dogrulanmis_uye(u uuid) returns boolean language sql stable as
                $$ select u is not null and exists(select 1 from auth.users where id=u) $$;
            insert into auth.users values('${owner}','owner@ogr.ktu.edu.tr'),('${reporter}','reporter@ogr.ktu.edu.tr');
            insert into public.fakulteler values(1,'Mühendislik');
            insert into public.bolumler values(10,'Bilgisayar Mühendisliği',1);
            insert into public.nk_dersler(id,bolum_id,ders_adi,ders_kodu,ekleyen_kullanici_id) values
                (100,10,'Bilgisayar Ağları','blm 301','${owner}'),(101,10,'Bilgisayar Ağları II','BLM-302','${owner}'),
                (102,10,'Ağlar Tekrarı','BLM 301','${owner}');
            insert into public.sorular(id,ders_id,kullanici_id,sinav_turu,akademik_yil,element_yollari,durum) values
                ('${q1}',100,'${owner}','final',2025,array['x.pdf'],'onaylandi'),
                ('${q2}',102,'${owner}','vize',2024,array['y.pdf'],'beklemede');
        `);
        const migration = fs.readFileSync('migrations/003_arsiv_moderasyon.sql','utf8');
        await db.exec(migration);
        await db.exec(migration);

        await t.test('Ders kodları tek biçime çevrilir ve yeni geçersiz kod reddedilir', async () => {
            const { rows } = await db.query('select id,ders_kodu,ders_kodu_standart from public.nk_dersler order by id');
            assert.deepEqual(rows.map(r => [r.id,r.ders_kodu,r.ders_kodu_standart]),
                [[100,'BLM301','BLM301'],[101,'BLM302','BLM302'],[102,'BLM301','BLM301']]);
            await assert.rejects(db.query("insert into public.nk_dersler(bolum_id,ders_adi,ders_kodu) values(10,'Bozuk','123')"),
                error => error.code === '23514');
            await assert.rejects(db.query("insert into public.nk_dersler(bolum_id,ders_adi,ders_kodu) values(10,'Yeni Ağlar','blm-302')"),
                error => error.code === '23505');
        });

        await db.query("select set_config('request.jwt.claim.sub',$1,false)",[reporter]);
        await t.test('Sayaç ve ders araması yalnız sayfalı özet döndürür', async () => {
            const counters = (await db.query('select public.nk_klasor_sayaclari() r')).rows[0].r;
            assert.equal(counters.fakulteler[0].soru_sayisi,1);
            const search = (await db.query("select public.nk_ders_ara(10,'ağ',3,0,'ad') r")).rows[0].r;
            assert.equal(Number(search.toplam),3);
            assert.equal(search.satirlar.length,3);
            assert.equal(search.satirlar.find(d => d.id === 100).soru_sayisi,1);
        });

        await t.test('Üye onaylı içeriği bir kez bildirebilir; kendi içeriğini bildiremez', async () => {
            const first = (await db.query("select public.nk_icerik_bildir($1,'yanlis_bilgi','Kontrol edilsin') r",[q1])).rows[0].r;
            assert.equal(first.basarili,true);
            const duplicate = (await db.query("select public.nk_icerik_bildir($1,'yanlis_bilgi',null) r",[q1])).rows[0].r;
            assert.equal(duplicate.hata,'zaten_bildirildi');
            await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);
            const own = (await db.query("select public.nk_icerik_bildir($1,'diger',null) r",[q1])).rows[0].r;
            assert.equal(own.hata,'kendi_icerigin');
        });

        await t.test('Moderasyon kararı gerekçeyi ve geçmişi saklar', async () => {
            const result = (await db.query("select public.admin_soru_modere_et('test-admin',$1,'reddedildi','yanlis_bilgi','Yanlış cevap anahtarı') r",[q1])).rows[0].r;
            assert.equal(result.basarili,true);
            const question = (await db.query('select durum,moderasyon_nedeni,moderasyon_notu from public.sorular where id=$1',[q1])).rows[0];
            assert.deepEqual(question,{durum:'reddedildi',moderasyon_nedeni:'yanlis_bilgi',moderasyon_notu:'Yanlış cevap anahtarı'});
            const history = (await db.query("select public.admin_nk_moderasyon_gecmisi('test-admin','soru',$1) r",[q1])).rows[0].r;
            assert.equal(history[0].neden,'yanlis_bilgi');
        });

        await t.test('Ders birleştirme soruları taşır, kaynak dersi siler ve iz bırakır', async () => {
            const result = (await db.query("select public.admin_nk_ders_birlestir('test-admin',102,100,'tekrar','Aynı ders') r")).rows[0].r;
            assert.equal(result.basarili,true);
            assert.equal(result.tasinan_soru,1);
            assert.equal((await db.query('select ders_id from public.sorular where id=$1',[q2])).rows[0].ders_id,100);
            assert.equal((await db.query('select count(*)::integer n from public.nk_dersler where id=102')).rows[0].n,0);
            const history = (await db.query("select public.admin_nk_moderasyon_gecmisi('test-admin','ders','102') r")).rows[0].r;
            assert.equal(history[0].iliskili_hedef_id,'100');
        });

        await t.test('Admin araması ve bildirim kuyruğu toplamla birlikte sayfalanır', async () => {
            const questions = (await db.query("select public.admin_soru_ara('test-admin',null,'ağ',1,0) r")).rows[0].r;
            assert.equal(Number(questions.toplam),2); assert.equal(questions.satirlar.length,1);
            const reports = (await db.query("select public.admin_nk_bildirim_listele('test-admin','kapatildi',10,0) r")).rows[0].r;
            assert.equal(Number(reports.toplam),1);
            assert.equal(reports.satirlar[0].durum,'kapatildi');
        });

        await t.test('Ders düzenleme ve kalıcı soru silme yönetim geçmişi bırakır', async () => {
            const edit = (await db.query("select public.admin_nk_ders_duzenle('test-admin',101,'Bilgisayar Ağları 2','blm.402') r")).rows[0].r;
            assert.equal(edit.basarili,true);
            const course = (await db.query('select ders_adi,ders_kodu from public.nk_dersler where id=101')).rows[0];
            assert.deepEqual(course,{ders_adi:'Bilgisayar Ağları 2',ders_kodu:'BLM402'});
            const courseHistory = (await db.query("select public.admin_nk_moderasyon_gecmisi('test-admin','ders','101') r")).rows[0].r;
            assert.equal(courseHistory[0].islem,'duzenlendi');

            const removed = (await db.query("select public.admin_soru_sil('test-admin',$1) r",[q2])).rows[0].r;
            assert.equal(removed.basarili,true);
            assert.equal((await db.query('select count(*)::integer n from public.sorular where id=$1',[q2])).rows[0].n,0);
            const questionHistory = (await db.query("select public.admin_nk_moderasyon_gecmisi('test-admin','soru',$1) r",[q2])).rows[0].r;
            assert.equal(questionHistory[0].islem,'silindi');
        });
    } finally { await db.close(); }
});
