const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');

test('Profil katkı sahipliği ve moderasyonlu düzeltme talebi sunucuda korunur',async()=>{
    const {PGlite}=await import('@electric-sql/pglite');
    const db=new PGlite();
    const owner='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
    try{
        await db.exec(`create role anon;create role authenticated;create schema auth;
            create table auth.users(id uuid primary key,email text);insert into auth.users values('${owner}','a@ogr.ktu.edu.tr'),('${other}','b@ogr.ktu.edu.tr');
            create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
            create function public.nk_dogrulanmis_uye(uuid) returns boolean language sql stable as $$select true$$;
            create function public._admin_token_gecerli_mi(text) returns boolean language sql stable as $$select $1='dogru'$$;
            create function public.nk_ders_kodu_standartlastir(text) returns text language sql immutable as $$select case when upper(regexp_replace(coalesce($1,''),'[^a-zA-Z0-9]','','g'))~'^[A-Z]{2,10}[0-9]{2,4}[A-Z]?$' then upper(regexp_replace($1,'[^a-zA-Z0-9]','','g')) end$$;
            create table public.fakulteler(id int primary key,ad text);create table public.bolumler(id int primary key,fakulte_id int,ad text);
            create table public.dersler(id bigint generated by default as identity primary key,bolum_id int,ders_adi text,ders_kodu text,onaylandi boolean default false);
            create table public.ders_verileri(id bigint generated by default as identity primary key,ders_id bigint,ortalama numeric,std_sapma numeric,ogrenci_sayisi int,can_turu text,donem text,yil int);
            create table public.nk_dersler(id bigint generated by default as identity primary key,ders_adi text,ders_kodu text,ekleyen_kullanici_id uuid);
            create table public.kayitli_donemler(id uuid primary key);
            insert into fakulteler values(1,'F');insert into bolumler values(1,1,'B');
            grant usage on schema public to authenticated;grant insert,select on public.dersler,public.ders_verileri to authenticated;
            grant usage,select on all sequences in schema public to authenticated;`);
        const sql=fs.readFileSync('migrations/006_profil_duzeltme_talepleri.sql','utf8');
        await db.exec(sql);await db.exec(sql);
        await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);set role authenticated;
            insert into public.dersler(bolum_id,ders_adi,ders_kodu,onaylandi) values(1,'Matematik','MAT101',true);
            insert into public.ders_verileri(ders_id,ortalama,std_sapma,ogrenci_sayisi,can_turu,donem,yil) values(1,55,12,40,'final','Güz',2026);`);
        const profil=(await db.query('select public.profil_katkilarim() r')).rows[0].r;
        assert.equal(profil.dersler[0].ders_adi,'Matematik');assert.equal(Number(profil.veriler[0].ortalama),55);
        const talep=(await db.query(`select public.duzeltme_talebi_olustur('ders_verisi','1','{"ortalama":60}'::jsonb,'Yanlış girdim') r`)).rows[0].r;
        assert.equal(talep.basarili,true);
        await db.exec(`reset role;select set_config('request.jwt.claim.sub','${other}',false);set role authenticated;`);
        const yabanci=(await db.query(`select public.duzeltme_talebi_olustur('ders_verisi','1','{"ortalama":70}'::jsonb,'Değişsin') r`)).rows[0].r;
        assert.equal(yabanci.hata,'yetkisiz');
        await db.exec('reset role');
        const liste=(await db.query("select public.admin_duzeltme_talepleri_listele('dogru','beklemede',30,0) r")).rows[0].r;
        assert.equal(Number(liste.satirlar[0].mevcut.ortalama),55);
        assert.equal(Number(liste.satirlar[0].oneri.ortalama),60);
        const id=(await db.query('select id from public.duzeltme_talepleri limit 1')).rows[0].id;
        const karar=(await db.query(`select public.admin_duzeltme_talebi_sonuclandir('dogru','${id}','onaylandi','Kontrol edildi') r`)).rows[0].r;
        assert.equal(karar.basarili,true);
        assert.equal(Number((await db.query('select ortalama from public.ders_verileri where id=1')).rows[0].ortalama),60);
        assert.equal((await db.query('select count(*)::integer n from public.katki_sahipligi')).rows[0].n,2);
    }finally{await db.close();}
});
