const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');

test('Paylaşım sahibi düzeltme ister, yönetici bilgileri ve sırayı güvenle düzenler',async()=>{
    const {PGlite}=await import('@electric-sql/pglite');
    const db=new PGlite();
    const owner='11111111-1111-4111-8111-111111111111';
    const other='22222222-2222-4222-8222-222222222222';
    const q1='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
    const q2='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
    try{
        await db.exec(`create role anon;create role authenticated;create schema auth;
            create table auth.users(id uuid primary key,email text);insert into auth.users values('${owner}','a@ogr.ktu.edu.tr'),('${other}','b@ogr.ktu.edu.tr');
            create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
            create function public.nk_dogrulanmis_uye(uuid) returns boolean language sql stable as $$select $1 is not null$$;
            create function public._admin_token_gecerli_mi(text) returns boolean language sql volatile as $$select $1='dogru'$$;
            create function public.nk_ders_kodu_standartlastir(text) returns text language sql immutable as $$select upper(nullif(regexp_replace(coalesce($1,''),'[^a-zA-Z0-9]','','g'),''))$$;
            create table public.kayitli_donemler(id uuid primary key);
            create table public.fakulteler(id int primary key,ad text);
            create table public.bolumler(id int primary key,fakulte_id int,ad text);
            create table public.dersler(id bigint generated by default as identity primary key,bolum_id int,ders_adi text,ders_kodu text,onaylandi boolean default false);
            create table public.ders_verileri(id bigint generated by default as identity primary key,ders_id bigint,ortalama numeric,std_sapma numeric,ogrenci_sayisi int,can_turu text,donem text,yil int);
            create table public.nk_dersler(id bigint generated by default as identity primary key,bolum_id int,ders_adi text,ders_kodu text,ekleyen_kullanici_id uuid,olusturulma_tarihi timestamptz default now());
            create table public.sorular(id uuid primary key,ders_id bigint,kullanici_id uuid,sinav_turu text,akademik_yil int,element_yollari text[],durum text,olusturulma_tarihi timestamptz default now(),moderasyon_nedeni text,moderasyon_notu text,moderasyon_tarihi timestamptz);
            create table public.nk_moderasyon_gecmisi(id bigint generated by default as identity,hedef_turu text,hedef_id text,islem text,onceki_durum text,yeni_durum text,neden text,aciklama text,olusturulma_tarihi timestamptz default now());
            insert into fakulteler values(1,'Mühendislik');insert into bolumler values(1,1,'Bilgisayar');
            insert into nk_dersler(bolum_id,ders_adi,ders_kodu,ekleyen_kullanici_id) values(1,'Ağlar','BLM301','${owner}');
            insert into sorular values('${q1}',1,'${owner}','vize',2024,array['x'],'onaylandi',now(),null,null,null),('${q2}',1,'${owner}','final',2025,array['y'],'onaylandi',now(),null,null,null);
            create function public.admin_soru_ara(text,text,text,integer,integer) returns jsonb language sql as $$select '{}'::jsonb$$;
            grant usage on schema public to authenticated;grant insert,select on public.dersler,public.ders_verileri to authenticated;
            grant usage,select on all sequences in schema public to authenticated;`);
        await db.exec(fs.readFileSync('migrations/006_profil_duzeltme_talepleri.sql','utf8'));
        const migration=fs.readFileSync('migrations/014_soru_duzenleme_ve_siralama.sql','utf8');
        await db.exec(migration);await db.exec(migration);

        await db.exec(`select set_config('request.jwt.claim.sub','${owner}',false);set role authenticated;`);
        const talep=(await db.query(`select public.duzeltme_talebi_olustur('soru','${q1}','{"sinav_turu":"final","akademik_yil":2025}'::jsonb,'Yılı yanlış seçtim') r`)).rows[0].r;
        assert.equal(talep.basarili,true);
        await db.exec(`reset role;select set_config('request.jwt.claim.sub','${other}',false);set role authenticated;`);
        const yabanci=(await db.query(`select public.duzeltme_talebi_olustur('soru','${q2}','{"akademik_yil":2023}'::jsonb,'Bence yanlış') r`)).rows[0].r;
        assert.equal(yabanci.hata,'yetkisiz');

        await db.exec('reset role');
        const dogrudan=(await db.query(`select public.admin_soru_duzenle('dogru','${q2}','ders_notu',2023,1) r`)).rows[0].r;
        assert.equal(dogrudan.basarili,true);
        const liste=(await db.query("select public.admin_soru_ara('dogru',null,null,25,0) r")).rows[0].r;
        const q2Satir=liste.satirlar.find(x=>x.id===q2);
        assert.equal(q2Satir.sinav_turu,'ders_notu');assert.equal(q2Satir.goruntuleme_sirasi,1);

        const talepId=(await db.query("select id from public.duzeltme_talepleri where hedef_turu='soru'")).rows[0].id;
        const karar=(await db.query(`select public.admin_duzeltme_talebi_sonuclandir('dogru','${talepId}','onaylandi','Bilgi doğrulandı') r`)).rows[0].r;
        assert.equal(karar.basarili,true);
        const guncel=(await db.query(`select sinav_turu,akademik_yil from public.sorular where id='${q1}'`)).rows[0];
        assert.deepEqual(guncel,{sinav_turu:'final',akademik_yil:2025});
        assert.equal(Number((await db.query("select count(*) n from public.nk_moderasyon_gecmisi where hedef_turu='soru'")).rows[0].n),2);
    }finally{await db.close();}
});

test('Not Kutusu görünümü oturum yenilemesinde korunur ve tarayıcı geçmişine bağlanır',()=>{
    const js=fs.readFileSync('src/scripts/not-kutusu.js','utf8');
    assert.match(js,/if \(!nkVeriYuklendi\) nkUyeVerileriniYukle\(\)/);
    assert.match(js,/history\[islem\]\(durum/);
    assert.match(js,/addEventListener\('popstate'/);
    assert.match(js,/sessionStorage\.setItem\(NK_KONUM_ANAHTARI/);
    assert.match(js,/id="nk-asama-geri"/);
});
