-- 002 sonrasında uygulanır: büyük arşiv sorguları, ders standardı ve moderasyon kaydı.
-- Veri silmez. Ders birleştirme yalnızca açık admin RPC çağrısıyla yapılır.
begin;

create or replace function public.nk_ders_kodu_standartlastir(p_kod text)
returns text language sql immutable set search_path = pg_catalog
as $$
    select case
        when nullif(btrim(p_kod), '') is null then null
        when regexp_replace(upper(translate(btrim(p_kod), 'çğıöşüÇĞİÖŞÜ', 'cgiosuCGIOSU')), '[^A-Z0-9]', '', 'g')
             ~ '^[A-Z]{2,10}[0-9]{2,4}[A-Z]?$'
        then regexp_replace(upper(translate(btrim(p_kod), 'çğıöşüÇĞİÖŞÜ', 'cgiosuCGIOSU')), '[^A-Z0-9]', '', 'g')
        else null
    end;
$$;

alter table public.nk_dersler add column if not exists ders_kodu_standart text;
update public.nk_dersler
set ders_kodu_standart = public.nk_ders_kodu_standartlastir(ders_kodu),
    ders_kodu = public.nk_ders_kodu_standartlastir(ders_kodu)
where public.nk_ders_kodu_standartlastir(ders_kodu) is not null
  and (ders_kodu is distinct from public.nk_ders_kodu_standartlastir(ders_kodu)
       or ders_kodu_standart is distinct from public.nk_ders_kodu_standartlastir(ders_kodu));
update public.nk_dersler
set ders_kodu_standart = null
where public.nk_ders_kodu_standartlastir(ders_kodu) is null
  and ders_kodu_standart is not null;
create index if not exists nk_dersler_bolum_kod_idx on public.nk_dersler(bolum_id, ders_kodu_standart)
    where ders_kodu_standart is not null;

create or replace function public.nk_ders_kodu_yaz()
returns trigger language plpgsql set search_path = pg_catalog, public
as $$
declare v text;
begin
    if nullif(btrim(new.ders_kodu), '') is null then
        new.ders_kodu := null; new.ders_kodu_standart := null; return new;
    end if;
    v := public.nk_ders_kodu_standartlastir(new.ders_kodu);
    if v is null then
        raise exception 'Ders kodu 2-10 harf ve ardından 2-4 rakam biçiminde olmalı (ör. BLM301).'
            using errcode = '23514';
    end if;
    if not (tg_op='UPDATE' and old.bolum_id=new.bolum_id and old.ders_kodu_standart=v)
       and exists(select 1 from public.nk_dersler d
                  where d.bolum_id=new.bolum_id and d.ders_kodu_standart=v
                    and d.id is distinct from new.id) then
        raise exception 'Bu bölümde % kodlu bir ders zaten var.', v using errcode = '23505';
    end if;
    new.ders_kodu := v; new.ders_kodu_standart := v;
    return new;
end; $$;
drop trigger if exists nk_ders_kodu_yaz on public.nk_dersler;
create trigger nk_ders_kodu_yaz before insert or update of ders_kodu, bolum_id on public.nk_dersler
for each row execute function public.nk_ders_kodu_yaz();

alter table public.sorular add column if not exists moderasyon_nedeni text;
alter table public.sorular add column if not exists moderasyon_notu text;
alter table public.sorular add column if not exists moderasyon_tarihi timestamptz;

create table if not exists public.nk_moderasyon_gecmisi (
    id bigint generated by default as identity primary key,
    hedef_turu text not null check (hedef_turu in ('soru','ders','bildirim')),
    hedef_id text not null,
    islem text not null check (islem in ('onaylandi','reddedildi','silindi','duzenlendi','birlestirildi','bildirim_kapatildi')),
    onceki_durum text,
    yeni_durum text,
    neden text not null check (neden in ('uygun','okunmuyor','yanlis_ders','yanlis_bilgi','tekrar','telif','kisisel_veri','spam','diger')),
    aciklama text,
    iliskili_hedef_id text,
    olusturulma_tarihi timestamptz not null default now(),
    check (aciklama is null or char_length(aciklama) <= 1000)
);
create index if not exists nk_moderasyon_hedef_idx
    on public.nk_moderasyon_gecmisi(hedef_turu, hedef_id, olusturulma_tarihi desc);
alter table public.nk_moderasyon_gecmisi enable row level security;
revoke all on public.nk_moderasyon_gecmisi from public, anon, authenticated;

create table if not exists public.nk_icerik_bildirimleri (
    id uuid primary key default gen_random_uuid(),
    soru_id uuid not null references public.sorular(id) on delete cascade,
    bildiren_kullanici_id uuid references auth.users(id) on delete set null,
    neden text not null check (neden in ('okunmuyor','yanlis_ders','yanlis_bilgi','tekrar','telif','kisisel_veri','spam','diger')),
    aciklama text,
    durum text not null default 'acik' check (durum in ('acik','kapatildi')),
    sonuc_notu text,
    olusturulma_tarihi timestamptz not null default now(),
    sonuclanma_tarihi timestamptz,
    check (aciklama is null or char_length(aciklama) <= 1000),
    check (sonuc_notu is null or char_length(sonuc_notu) <= 1000)
);
create unique index if not exists nk_icerik_bildirim_acik_unique
    on public.nk_icerik_bildirimleri(soru_id, bildiren_kullanici_id) where durum='acik';
create index if not exists nk_icerik_bildirim_durum_idx
    on public.nk_icerik_bildirimleri(durum, olusturulma_tarihi desc);
alter table public.nk_icerik_bildirimleri enable row level security;
revoke all on public.nk_icerik_bildirimleri from public, anon, authenticated;

-- Fakülte/bölüm sayaçları tek sunucu sorgusunda hesaplanır; soru kimlikleri tarayıcıya taşınmaz.
create or replace function public.nk_klasor_sayaclari()
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public
as $$
declare u uuid := auth.uid(); sonuc jsonb;
begin
    if not public.nk_dogrulanmis_uye(u) then raise exception 'yetkisiz'; end if;
    select jsonb_build_object(
        'fakulteler', coalesce((select jsonb_agg(to_jsonb(x) order by x.id) from (
            select f.id, count(distinct d.id)::integer as ders_sayisi,
                   count(distinct s.id)::integer as soru_sayisi
            from public.fakulteler f left join public.bolumler b on b.fakulte_id=f.id
            left join public.nk_dersler d on d.bolum_id=b.id
            left join public.sorular s on s.ders_id=d.id and s.durum='onaylandi'
            group by f.id) x), '[]'::jsonb),
        'bolumler', coalesce((select jsonb_agg(to_jsonb(x) order by x.id) from (
            select b.id, count(distinct d.id)::integer as ders_sayisi,
                   count(distinct s.id)::integer as soru_sayisi
            from public.bolumler b left join public.nk_dersler d on d.bolum_id=b.id
            left join public.sorular s on s.ders_id=d.id and s.durum='onaylandi'
            group by b.id) x), '[]'::jsonb)
    ) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.nk_klasor_sayaclari() from public, anon;
grant execute on function public.nk_klasor_sayaclari() to authenticated;

create or replace function public.nk_ders_ara(
    p_bolum_id integer, p_arama text default null, p_limit integer default 24, p_offset integer default 0,
    p_siralama text default 'ad')
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public
as $$
declare u uuid := auth.uid(); l integer := least(greatest(coalesce(p_limit,24),1),50);
    o integer := greatest(coalesce(p_offset,0),0); q text := lower(nullif(btrim(p_arama),'')); sonuc jsonb;
begin
    if not public.nk_dogrulanmis_uye(u) then raise exception 'yetkisiz'; end if;
    with eslesen as (
        select d.id,d.bolum_id,d.ders_adi,d.ders_kodu,d.ders_kodu_standart,
               count(s.id) filter (where s.durum='onaylandi')::integer as soru_sayisi
        from public.nk_dersler d left join public.sorular s on s.ders_id=d.id
        where d.bolum_id=p_bolum_id and (q is null or lower(d.ders_adi) like '%'||q||'%'
              or lower(coalesce(d.ders_kodu_standart,d.ders_kodu,'')) like '%'||q||'%')
        group by d.id
    ), sayfa as (
        select * from eslesen order by case when p_siralama='soru' then soru_sayisi end desc, ders_adi, id limit l offset o
    )
    select jsonb_build_object('toplam',(select count(*) from eslesen),
        'satirlar',coalesce((select jsonb_agg(to_jsonb(sayfa) order by ders_adi,id) from sayfa),'[]'::jsonb)) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.nk_ders_ara(integer,text,integer,integer,text) from public, anon;
grant execute on function public.nk_ders_ara(integer,text,integer,integer,text) to authenticated;

create or replace function public.nk_icerik_bildir(p_soru_id uuid, p_neden text, p_aciklama text default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public
as $$
declare u uuid := auth.uid(); sahip uuid; yeni_id uuid;
begin
    if not public.nk_dogrulanmis_uye(u) then return jsonb_build_object('hata','yetkisiz'); end if;
    if p_neden not in ('okunmuyor','yanlis_ders','yanlis_bilgi','tekrar','telif','kisisel_veri','spam','diger')
       or char_length(coalesce(p_aciklama,''))>1000 then return jsonb_build_object('hata','gecersiz_bildirim'); end if;
    select kullanici_id into sahip from public.sorular where id=p_soru_id and durum='onaylandi';
    if not found then return jsonb_build_object('hata','bulunamadi'); end if;
    if sahip=u then return jsonb_build_object('hata','kendi_icerigin'); end if;
    if (select count(*) from public.nk_icerik_bildirimleri where bildiren_kullanici_id=u
        and olusturulma_tarihi>now()-interval '24 hours')>=10 then return jsonb_build_object('hata','sinir_asildi'); end if;
    begin
        insert into public.nk_icerik_bildirimleri(soru_id,bildiren_kullanici_id,neden,aciklama)
        values(p_soru_id,u,p_neden,nullif(btrim(p_aciklama),'')) returning id into yeni_id;
    exception when unique_violation then return jsonb_build_object('hata','zaten_bildirildi'); end;
    return jsonb_build_object('basarili',true,'id',yeni_id);
end; $$;
revoke all on function public.nk_icerik_bildir(uuid,text,text) from public, anon;
grant execute on function public.nk_icerik_bildir(uuid,text,text) to authenticated;

create or replace function public.admin_soru_ara(p_admin_token text, p_durum text default null,
    p_arama text default null, p_limit integer default 25, p_offset integer default 0)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public
as $$
declare l integer := least(greatest(coalesce(p_limit,25),1),100); o integer := greatest(coalesce(p_offset,0),0);
    q text := lower(nullif(btrim(p_arama),'')); sonuc jsonb;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then raise exception 'yetkisiz'; end if;
    with eslesen as (
        select s.id,s.ders_id,d.ders_adi,d.ders_kodu,b.ad bolum_adi,f.ad fakulte_adi,u.email kullanici_email,
            s.kullanici_id,s.sinav_turu,s.akademik_yil,s.element_yollari,s.durum,s.olusturulma_tarihi,
            s.moderasyon_nedeni,s.moderasyon_notu,s.moderasyon_tarihi
        from public.sorular s join public.nk_dersler d on d.id=s.ders_id
        join public.bolumler b on b.id=d.bolum_id join public.fakulteler f on f.id=b.fakulte_id
        left join auth.users u on u.id=s.kullanici_id
        where (p_durum is null or p_durum='' or s.durum=p_durum)
          and (q is null or lower(d.ders_adi) like '%'||q||'%' or lower(coalesce(d.ders_kodu,'')) like '%'||q||'%'
               or lower(coalesce(u.email,'')) like '%'||q||'%')
    ), sayfa as (select * from eslesen order by olusturulma_tarihi desc,id limit l offset o)
    select jsonb_build_object('toplam',(select count(*) from eslesen),
        'satirlar',coalesce((select jsonb_agg(to_jsonb(sayfa) order by olusturulma_tarihi desc,id) from sayfa),'[]'::jsonb)) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.admin_soru_ara(text,text,text,integer,integer) from public;
grant execute on function public.admin_soru_ara(text,text,text,integer,integer) to anon, authenticated;

create or replace function public.admin_soru_modere_et(p_admin_token text,p_id uuid,p_karar text,p_neden text,p_not text default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public
as $$
declare eski text;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then return jsonb_build_object('hata','yetkisiz'); end if;
    if p_karar not in ('onaylandi','reddedildi') or p_neden not in
       ('uygun','okunmuyor','yanlis_ders','yanlis_bilgi','tekrar','telif','kisisel_veri','spam','diger')
       or (p_karar='reddedildi' and p_neden='uygun') or char_length(coalesce(p_not,''))>1000 then
        return jsonb_build_object('hata','gecersiz_karar'); end if;
    select durum into eski from public.sorular where id=p_id for update;
    if not found then return jsonb_build_object('hata','bulunamadi'); end if;
    update public.sorular set durum=p_karar,moderasyon_nedeni=p_neden,
        moderasyon_notu=nullif(btrim(p_not),''),moderasyon_tarihi=now() where id=p_id;
    insert into public.nk_moderasyon_gecmisi(hedef_turu,hedef_id,islem,onceki_durum,yeni_durum,neden,aciklama)
        values('soru',p_id::text,p_karar,eski,p_karar,p_neden,nullif(btrim(p_not),''));
    if p_karar='reddedildi' then
        update public.nk_icerik_bildirimleri set durum='kapatildi',sonuclanma_tarihi=now(),sonuc_notu='İçerik reddedildi.'
        where soru_id=p_id and durum='acik';
    end if;
    return jsonb_build_object('basarili',true);
end; $$;
revoke all on function public.admin_soru_modere_et(text,uuid,text,text,text) from public;
grant execute on function public.admin_soru_modere_et(text,uuid,text,text,text) to anon, authenticated;

create or replace function public.admin_soru_onayla(p_admin_token text,p_id uuid)
returns json language plpgsql security definer set search_path = pg_catalog, public
as $$ begin return public.admin_soru_modere_et(p_admin_token,p_id,'onaylandi','uygun',null)::json; end; $$;
create or replace function public.admin_soru_reddet(p_admin_token text,p_id uuid)
returns json language plpgsql security definer set search_path = pg_catalog, public
as $$ begin return public.admin_soru_modere_et(p_admin_token,p_id,'reddedildi','diger','Eski panel çağrısı')::json; end; $$;

create or replace function public.admin_nk_moderasyon_gecmisi(p_admin_token text,p_hedef_turu text,p_hedef_id text)
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public
as $$ declare sonuc jsonb; begin
    if not public._admin_token_gecerli_mi(p_admin_token) then raise exception 'yetkisiz'; end if;
    select coalesce(jsonb_agg(to_jsonb(g) order by g.olusturulma_tarihi desc),'[]'::jsonb) into sonuc
    from (select id,islem,onceki_durum,yeni_durum,neden,aciklama,iliskili_hedef_id,olusturulma_tarihi
          from public.nk_moderasyon_gecmisi where hedef_turu=p_hedef_turu and hedef_id=p_hedef_id
          order by olusturulma_tarihi desc limit 100) g;
    return sonuc;
end; $$;
revoke all on function public.admin_nk_moderasyon_gecmisi(text,text,text) from public;
grant execute on function public.admin_nk_moderasyon_gecmisi(text,text,text) to anon, authenticated;

create or replace function public.admin_nk_ders_ara(p_admin_token text,p_arama text default null,
    p_limit integer default 50,p_offset integer default 0,p_bolum_id integer default null)
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public
as $$
declare l integer:=least(greatest(coalesce(p_limit,50),1),100);o integer:=greatest(coalesce(p_offset,0),0);
    q text:=lower(nullif(btrim(p_arama),''));sonuc jsonb;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then raise exception 'yetkisiz'; end if;
    with eslesen as (
        select d.id,d.bolum_id,d.ders_adi,d.ders_kodu,d.ders_kodu_standart,d.olusturulma_tarihi,
            b.ad bolum_adi,f.ad fakulte_adi,u.email ekleyen_email,count(s.id)::integer soru_sayisi
        from public.nk_dersler d join public.bolumler b on b.id=d.bolum_id join public.fakulteler f on f.id=b.fakulte_id
        left join auth.users u on u.id=d.ekleyen_kullanici_id left join public.sorular s on s.ders_id=d.id
        where (p_bolum_id is null or d.bolum_id=p_bolum_id) and (q is null or lower(d.ders_adi) like '%'||q||'%'
            or lower(coalesce(d.ders_kodu,'')) like '%'||q||'%') group by d.id,b.ad,f.ad,u.email
    ), sayfa as (select * from eslesen order by ders_adi,id limit l offset o)
    select jsonb_build_object('toplam',(select count(*) from eslesen),
      'satirlar',coalesce((select jsonb_agg(to_jsonb(sayfa) order by ders_adi,id) from sayfa),'[]'::jsonb)) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.admin_nk_ders_ara(text,text,integer,integer,integer) from public;
grant execute on function public.admin_nk_ders_ara(text,text,integer,integer,integer) to anon, authenticated;

create or replace function public.admin_nk_ders_birlestir(p_admin_token text,p_kaynak_id integer,p_hedef_id integer,
    p_neden text default 'tekrar',p_not text default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public
as $$
declare kaynak public.nk_dersler;hedef public.nk_dersler;tasinan integer;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then return jsonb_build_object('hata','yetkisiz'); end if;
    if p_kaynak_id=p_hedef_id or p_neden not in ('tekrar','yanlis_ders','diger') or char_length(coalesce(p_not,''))>1000
        then return jsonb_build_object('hata','gecersiz_birlestirme'); end if;
    perform pg_advisory_xact_lock(least(p_kaynak_id,p_hedef_id));
    perform pg_advisory_xact_lock(greatest(p_kaynak_id,p_hedef_id));
    select * into kaynak from public.nk_dersler where id=p_kaynak_id;
    select * into hedef from public.nk_dersler where id=p_hedef_id;
    if kaynak.id is null or hedef.id is null then return jsonb_build_object('hata','bulunamadi'); end if;
    if kaynak.bolum_id<>hedef.bolum_id then return jsonb_build_object('hata','farkli_bolum'); end if;
    update public.sorular set ders_id=p_hedef_id where ders_id=p_kaynak_id; get diagnostics tasinan=row_count;
    insert into public.nk_moderasyon_gecmisi(hedef_turu,hedef_id,islem,neden,aciklama,iliskili_hedef_id)
        values('ders',p_kaynak_id::text,'birlestirildi',p_neden,nullif(btrim(p_not),''),p_hedef_id::text);
    delete from public.nk_dersler where id=p_kaynak_id;
    return jsonb_build_object('basarili',true,'tasinan_soru',tasinan,'hedef_id',p_hedef_id);
end; $$;
revoke all on function public.admin_nk_ders_birlestir(text,integer,integer,text,text) from public;
grant execute on function public.admin_nk_ders_birlestir(text,integer,integer,text,text) to anon, authenticated;

create or replace function public.admin_nk_ders_duzenle(p_admin_token text,p_id integer,p_ders_adi text,p_ders_kodu text default null)
returns json language plpgsql security definer set search_path = pg_catalog, public
as $$
declare eski public.nk_dersler;yeni public.nk_dersler;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then return json_build_object('hata','yetkisiz'); end if;
    if nullif(btrim(p_ders_adi),'') is null or char_length(btrim(p_ders_adi))>150 then
        return json_build_object('hata','gecersiz_ders_adi'); end if;
    select * into eski from public.nk_dersler where id=p_id for update;
    if eski.id is null then return json_build_object('hata','bulunamadi'); end if;
    update public.nk_dersler set ders_adi=btrim(p_ders_adi),ders_kodu=nullif(btrim(coalesce(p_ders_kodu,'')),'')
        where id=p_id returning * into yeni;
    insert into public.nk_moderasyon_gecmisi(hedef_turu,hedef_id,islem,onceki_durum,yeni_durum,neden,aciklama)
        values('ders',p_id::text,'duzenlendi',concat_ws(' — ',eski.ders_kodu,eski.ders_adi),
            concat_ws(' — ',yeni.ders_kodu,yeni.ders_adi),'diger','Ders bilgileri güncellendi.');
    return json_build_object('basarili',true);
exception when check_violation then
    return json_build_object('hata','gecersiz_ders_kodu');
when unique_violation then
    return json_build_object('hata','tekrar_ders_kodu');
end; $$;
revoke all on function public.admin_nk_ders_duzenle(text,integer,text,text) from public;
grant execute on function public.admin_nk_ders_duzenle(text,integer,text,text) to anon, authenticated;

create or replace function public.admin_soru_sil(p_admin_token text,p_id uuid)
returns json language plpgsql security definer set search_path = pg_catalog, public
as $$
declare eski text;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then return json_build_object('hata','yetkisiz'); end if;
    select durum into eski from public.sorular where id=p_id for update;
    if not found then return json_build_object('hata','bulunamadi'); end if;
    insert into public.nk_moderasyon_gecmisi(hedef_turu,hedef_id,islem,onceki_durum,neden,aciklama)
        values('soru',p_id::text,'silindi',eski,'diger','İçerik yönetici tarafından kalıcı olarak silindi.');
    delete from public.sorular where id=p_id;
    return json_build_object('basarili',true);
end; $$;
revoke all on function public.admin_soru_sil(text,uuid) from public;
grant execute on function public.admin_soru_sil(text,uuid) to anon, authenticated;

create or replace function public.admin_nk_bildirim_listele(p_admin_token text,p_durum text default 'acik',
    p_limit integer default 25,p_offset integer default 0)
returns jsonb language plpgsql stable security definer set search_path = pg_catalog, public
as $$
declare l integer:=least(greatest(coalesce(p_limit,25),1),100);o integer:=greatest(coalesce(p_offset,0),0);sonuc jsonb;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then raise exception 'yetkisiz'; end if;
    with eslesen as (
        select r.id,r.soru_id,r.neden,r.aciklama,r.durum,r.sonuc_notu,r.olusturulma_tarihi,r.sonuclanma_tarihi,
            u.email bildiren_email,s.durum soru_durumu,d.ders_adi,d.ders_kodu
        from public.nk_icerik_bildirimleri r join public.sorular s on s.id=r.soru_id
        join public.nk_dersler d on d.id=s.ders_id left join auth.users u on u.id=r.bildiren_kullanici_id
        where p_durum is null or p_durum='' or r.durum=p_durum
    ), sayfa as (select * from eslesen order by olusturulma_tarihi desc,id limit l offset o)
    select jsonb_build_object('toplam',(select count(*) from eslesen),
      'satirlar',coalesce((select jsonb_agg(to_jsonb(sayfa) order by olusturulma_tarihi desc,id) from sayfa),'[]'::jsonb)) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.admin_nk_bildirim_listele(text,text,integer,integer) from public;
grant execute on function public.admin_nk_bildirim_listele(text,text,integer,integer) to anon, authenticated;

create or replace function public.admin_nk_bildirim_kapat(p_admin_token text,p_id uuid,p_not text default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog, public
as $$
declare hedef uuid;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then return jsonb_build_object('hata','yetkisiz'); end if;
    if char_length(coalesce(p_not,''))>1000 then return jsonb_build_object('hata','gecersiz_not'); end if;
    update public.nk_icerik_bildirimleri set durum='kapatildi',sonuc_notu=nullif(btrim(p_not),''),sonuclanma_tarihi=now()
        where id=p_id and durum='acik' returning soru_id into hedef;
    if hedef is null then return jsonb_build_object('hata','bulunamadi'); end if;
    insert into public.nk_moderasyon_gecmisi(hedef_turu,hedef_id,islem,neden,aciklama,iliskili_hedef_id)
        values('bildirim',p_id::text,'bildirim_kapatildi','diger',nullif(btrim(p_not),''),hedef::text);
    return jsonb_build_object('basarili',true);
end; $$;
revoke all on function public.admin_nk_bildirim_kapat(text,uuid,text) from public;
grant execute on function public.admin_nk_bildirim_kapat(text,uuid,text) to anon, authenticated;

commit;

-- Dağıtım öncesi elle inceleme: aynı bölümde aynı standart kodu kullanan dersler.
select bolum_id,ders_kodu_standart,array_agg(id order by id) ders_idleri,array_agg(ders_adi order by id) ders_adlari
from public.nk_dersler where ders_kodu_standart is not null
group by bolum_id,ders_kodu_standart having count(*)>1;
