-- 003 sonrasında uygulanır: kayıtlı dönemler, AGNO planları ve güvenli işletim hata özeti.
begin;

create or replace function public.gano_dersler_gecerli(p_dersler jsonb)
returns boolean language plpgsql immutable set search_path = pg_catalog
as $$
declare d jsonb;
begin
    if jsonb_typeof(p_dersler)<>'array' or jsonb_array_length(p_dersler)>50 then return false; end if;
    for d in select value from jsonb_array_elements(p_dersler) loop
        if jsonb_typeof(d)<>'object'
           or length(coalesce(d->>'ad',''))>120
           or not coalesce(d ? 'kredi',false)
           or not coalesce(d ? 'not',false)
           or (d->>'kredi')!~'^[0-9]+([.][0-9]+)?$'
           or (d->>'kredi')::numeric not between 0.5 and 30
           or d->>'not' not in ('AA','BA','BB','CB','CC','DC','DD','FD','FF','D','G','K') then
            return false;
        end if;
    end loop;
    return true;
exception when others then return false;
end; $$;

create table if not exists public.kayitli_donemler (
    id uuid primary key default gen_random_uuid(),
    kullanici_id uuid not null references auth.users(id) on delete cascade,
    ad text not null check (char_length(btrim(ad)) between 1 and 80),
    akademik_yil integer not null check (akademik_yil between 2000 and 2100),
    donem text not null check (donem in ('guz','bahar','yaz')),
    dersler jsonb not null default '[]'::jsonb check (public.gano_dersler_gecerli(dersler)),
    mevcut_agno numeric(4,2) check (mevcut_agno between 0 and 4),
    mevcut_kredi numeric(7,2) check (mevcut_kredi between 0 and 9999),
    hedef_agno numeric(4,2) check (hedef_agno between 0 and 4),
    olusturulma_tarihi timestamptz not null default now(),
    guncelleme_tarihi timestamptz not null default now(),
    unique(kullanici_id,ad)
);
create index if not exists kayitli_donemler_kullanici_idx
    on public.kayitli_donemler(kullanici_id,guncelleme_tarihi desc);
create or replace function public.kayitli_donem_limit_kontrol()
returns trigger language plpgsql security definer set search_path = pg_catalog,public
as $$ begin
    if (select count(*) from public.kayitli_donemler where kullanici_id=new.kullanici_id)>=20 then
        raise exception 'En fazla 20 dönem kaydedilebilir.' using errcode='23514';
    end if;
    return new;
end; $$;
drop trigger if exists kayitli_donem_limit_kontrol on public.kayitli_donemler;
create trigger kayitli_donem_limit_kontrol before insert on public.kayitli_donemler
for each row execute function public.kayitli_donem_limit_kontrol();
alter table public.kayitli_donemler enable row level security;
drop policy if exists kayitli_donemler_select_own on public.kayitli_donemler;
create policy kayitli_donemler_select_own on public.kayitli_donemler for select to authenticated
    using (kullanici_id=auth.uid() and public.nk_dogrulanmis_uye(auth.uid()));
drop policy if exists kayitli_donemler_insert_own on public.kayitli_donemler;
create policy kayitli_donemler_insert_own on public.kayitli_donemler for insert to authenticated
    with check (kullanici_id=auth.uid() and public.nk_dogrulanmis_uye(auth.uid()));
drop policy if exists kayitli_donemler_update_own on public.kayitli_donemler;
create policy kayitli_donemler_update_own on public.kayitli_donemler for update to authenticated
    using (kullanici_id=auth.uid() and public.nk_dogrulanmis_uye(auth.uid()))
    with check (kullanici_id=auth.uid() and public.nk_dogrulanmis_uye(auth.uid()));
drop policy if exists kayitli_donemler_delete_own on public.kayitli_donemler;
create policy kayitli_donemler_delete_own on public.kayitli_donemler for delete to authenticated
    using (kullanici_id=auth.uid() and public.nk_dogrulanmis_uye(auth.uid()));
revoke all on public.kayitli_donemler from public,anon;
grant select,insert,update,delete on public.kayitli_donemler to authenticated;

create or replace function public.kayitli_donem_guncelleme_tarihi()
returns trigger language plpgsql set search_path = pg_catalog
as $$ begin new.guncelleme_tarihi=now(); return new; end; $$;
drop trigger if exists kayitli_donem_guncelleme_tarihi on public.kayitli_donemler;
create trigger kayitli_donem_guncelleme_tarihi before update on public.kayitli_donemler
for each row execute function public.kayitli_donem_guncelleme_tarihi();

create table if not exists public.uygulama_hatalari (
    id bigint generated by default as identity primary key,
    kullanici_id uuid not null references auth.users(id) on delete cascade,
    kategori text not null check (kategori in ('javascript','ag','veritabani','dosya','gano')),
    kod text not null check (kod~'^[a-z0-9_.-]{1,80}$'),
    mesaj text not null check (char_length(mesaj) between 1 and 300),
    sayfa text not null check (sayfa~'^/[a-zA-Z0-9._/-]{0,160}$'),
    surum text check (surum is null or surum~'^[a-zA-Z0-9._-]{1,40}$'),
    olusturulma_tarihi timestamptz not null default now()
);
create index if not exists uygulama_hatalari_tarih_idx on public.uygulama_hatalari(olusturulma_tarihi desc);
create index if not exists uygulama_hatalari_kod_idx on public.uygulama_hatalari(kod,olusturulma_tarihi desc);
alter table public.uygulama_hatalari enable row level security;
revoke all on public.uygulama_hatalari from public,anon,authenticated;

create or replace function public.uygulama_hatasi_kaydet(p_kategori text,p_kod text,p_mesaj text,p_sayfa text,p_surum text default null)
returns jsonb language plpgsql security definer set search_path = pg_catalog,public
as $$
declare u uuid:=auth.uid(); temiz text;
begin
    if not public.nk_dogrulanmis_uye(u) then return jsonb_build_object('hata','yetkisiz'); end if;
    if p_kategori not in ('javascript','ag','veritabani','dosya','gano') or coalesce(p_kod,'')!~'^[a-z0-9_.-]{1,80}$'
       or coalesce(p_sayfa,'')!~'^/[a-zA-Z0-9._/-]{0,160}$'
       or (p_surum is not null and p_surum!~'^[a-zA-Z0-9._-]{1,40}$') then
        return jsonb_build_object('hata','gecersiz_veri'); end if;
    if (select count(*) from public.uygulama_hatalari where kullanici_id=u and olusturulma_tarihi>now()-interval '24 hours')>=30 then
        return jsonb_build_object('hata','sinir_asildi'); end if;
    temiz:=left(regexp_replace(regexp_replace(regexp_replace(coalesce(p_mesaj,'Bilinmeyen hata'),
        '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+[.][A-Za-z]{2,}','[eposta]','g'),
        'https?://[^ ]+','[url]','g'),'eyJ[A-Za-z0-9_-]+[.][A-Za-z0-9_-]+[.][A-Za-z0-9_-]+','[token]','g'),300);
    insert into public.uygulama_hatalari(kullanici_id,kategori,kod,mesaj,sayfa,surum)
        values(u,p_kategori,p_kod,temiz,p_sayfa,nullif(p_surum,''));
    return jsonb_build_object('basarili',true);
end; $$;
revoke all on function public.uygulama_hatasi_kaydet(text,text,text,text,text) from public,anon;
grant execute on function public.uygulama_hatasi_kaydet(text,text,text,text,text) to authenticated;

create or replace function public.admin_isletim_ozeti(p_admin_token text)
returns jsonb language plpgsql stable security definer set search_path = pg_catalog,public
as $$ declare sonuc jsonb; begin
    if not public._admin_token_gecerli_mi(p_admin_token) then raise exception 'yetkisiz'; end if;
    select jsonb_build_object(
        'son_24_saat',(select count(*) from public.uygulama_hatalari where olusturulma_tarihi>now()-interval '24 hours'),
        'son_7_gun',(select count(*) from public.uygulama_hatalari where olusturulma_tarihi>now()-interval '7 days'),
        'temizlik_bekleyen',(select count(*) from public.nk_dosyalar where durum='deleting'),
        'tekrarli_hatalar',coalesce((select jsonb_agg(to_jsonb(x) order by x.adet desc,x.kod) from (
            select kategori,kod,left(max(mesaj),160) mesaj,count(*)::integer adet,max(olusturulma_tarihi) son_tarih
            from public.uygulama_hatalari where olusturulma_tarihi>now()-interval '7 days'
            group by kategori,kod order by count(*) desc,max(olusturulma_tarihi) desc limit 10) x),'[]'::jsonb)
    ) into sonuc;
    return sonuc;
end; $$;
revoke all on function public.admin_isletim_ozeti(text) from public;
grant execute on function public.admin_isletim_ozeti(text) to anon,authenticated;

create or replace function public.uygulama_hatasi_temizle()
returns integer language plpgsql security definer set search_path = pg_catalog,public
as $$ declare n integer; begin delete from public.uygulama_hatalari where olusturulma_tarihi<now()-interval '90 days'; get diagnostics n=row_count; return n; end; $$;
revoke all on function public.uygulama_hatasi_temizle() from public,anon,authenticated;
grant execute on function public.uygulama_hatasi_temizle() to service_role;

commit;
