-- ============================================================
-- NOT KUTUSU — Klasör Sistemi Migrasyonu (Fakülte > Bölüm > Ders)
-- ============================================================
-- Bu dosya, Not Kutusu'nun tasarımını değiştiren isteğe karşılık geliyor:
--   1) Dersler artık "Ders Verileri" özelliğinin (grade-calculator) paylaştığı
--      `public.dersler` tablosundan GELMİYOR. Bunun yerine, Not Kutusu'na özel,
--      BOŞ başlayan yeni bir `public.nk_dersler` tablosu var — kullanıcılar
--      "Dersim listede yok" diyerek kendi ekliyor.
--   2) Kullanıcının seçimiyle: yeni eklenen ders ONAY BEKLEMİYOR, eklendiği anda
--      herkese görünür oluyor (moderasyonsuz). Bu, yanlış yazılmış/tekrarlı ders
--      adı riski taşıyor — bunu azaltmak için bölüm başına (case-insensitive,
--      boşluk kırpılmış) TEKİL bir isim kısıtı eklendi; admin'in elle temizlik
--      yapabilmesi için de admin_nk_ders_sil / admin_nk_ders_duzenle RPC'leri var
--      (henüz admin paneline bir sekme olarak bağlanmadı — SQL Editor'den
--      admin_token ile çağrılabilir, istenirse panele de eklenir).
--
-- public.sorular.ders_id artık `dersler` yerine `nk_dersler`e işaret eder.
-- Eski derslere bağlı soru varsa işlem durur; otomatik veri silinmez.
-- Kurulu projeleri güncellerken migrations/ altındaki dosyaları kullanın.

begin;

-- ------------------------------------------------------------
-- 1) nk_dersler tablosu
-- ------------------------------------------------------------
create table if not exists public.nk_dersler (
    id integer generated by default as identity primary key,
    bolum_id integer not null references public.bolumler(id) on delete cascade,
    ders_adi text not null,
    ders_kodu text,
    ekleyen_kullanici_id uuid default auth.uid() references auth.users(id) on delete set null,
    olusturulma_tarihi timestamptz not null default now(),
    constraint nk_dersler_ad_uzunluk check (char_length(trim(ders_adi)) between 2 and 120)
);

create index if not exists nk_dersler_bolum_id_idx on public.nk_dersler (bolum_id);

-- Bölüm başına aynı ders adının (büyük/küçük harf ve baş/son boşluk farkı gözetmeksizin)
-- birden fazla eklenmesini engeller. İstemci tarafı (not-kutusu.js) bu ihlali (23505)
-- yakalayıp kullanıcıyı zaten var olan derse yönlendiriyor.
create unique index if not exists nk_dersler_bolum_ad_unique
    on public.nk_dersler (bolum_id, lower(trim(ders_adi)));

alter table public.nk_dersler enable row level security;

drop policy if exists "nk_dersler_select_uye" on public.nk_dersler;
create policy "nk_dersler_select_uye" on public.nk_dersler
    for select
    to authenticated
    using (public.is_ktu_uyesi());

drop policy if exists "nk_dersler_insert_uye" on public.nk_dersler;
create policy "nk_dersler_insert_uye" on public.nk_dersler
    for insert
    to authenticated
    with check (
        public.is_ktu_uyesi()
        and ekleyen_kullanici_id = auth.uid()
    );

-- Update/Delete için kullanıcılara hiç policy YOK — moderasyonsuz olduğu için
-- herkes ekleyebilir ama sadece admin (SECURITY DEFINER RPC ile) silebilir/düzeltebilir.

-- ------------------------------------------------------------
-- 2) sorular.ders_id artık nk_dersler'e işaret ediyor
-- ------------------------------------------------------------
-- Eski ders eşlemesini otomatik silmek yerine işlemi durdur.
-- Mevcut kurulumlar için migrations/001_not_kutusu_guvenlik.sql kullanılır.
do $$
begin
    if exists (select 1 from public.sorular) and exists (
        select 1 from pg_constraint
        where conrelid = 'public.sorular'::regclass
          and conname = 'sorular_ders_id_fkey'
          and confrelid <> 'public.nk_dersler'::regclass
    ) then
        raise exception 'Mevcut sorular var. Önce eski dersleri yeni derslerle eşleştirin; veri silinmedi.';
    end if;
end $$;

alter table public.sorular drop constraint if exists sorular_ders_id_fkey;
alter table public.sorular
    add constraint sorular_ders_id_fkey
    foreign key (ders_id) references public.nk_dersler(id) on delete restrict;

-- ------------------------------------------------------------
-- 3) admin_soru_listele GÜNCELLENDİ — artık dersler değil nk_dersler'e join ediyor
--    (supabase-not-kutusu-admin-rpc.sql'deki eski tanımın yerine geçer, aynı imza)
-- ------------------------------------------------------------
create or replace function public.admin_soru_listele(p_admin_token text, p_durum text default 'beklemede')
returns json
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
declare
    sonuc json;
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then
        raise exception 'yetkisiz';
    end if;

    select coalesce(json_agg(x.satir order by x.olusturulma_tarihi asc), '[]'::json)
    into sonuc
    from (
        select
            s.olusturulma_tarihi,
            json_build_object(
                'id', s.id,
                'ders_id', s.ders_id,
                'ders_adi', d.ders_adi,
                'ders_kodu', d.ders_kodu,
                'bolum_adi', b.ad,
                'fakulte_adi', f.ad,
                'kullanici_email', u.email,
                'sinav_turu', s.sinav_turu,
                'akademik_yil', s.akademik_yil,
                'fotograf_yolu', s.fotograf_yolu,
                'durum', s.durum,
                'olusturulma_tarihi', s.olusturulma_tarihi
            ) as satir
        from public.sorular s
        join public.nk_dersler d on d.id = s.ders_id
        join public.bolumler b on b.id = d.bolum_id
        join public.fakulteler f on f.id = b.fakulte_id
        left join auth.users u on u.id = s.kullanici_id
        where p_durum is null or s.durum = p_durum
    ) x;

    return sonuc;
end;
$function$;

-- ------------------------------------------------------------
-- 4) Admin temizlik RPC'leri (moderasyonsuz ders ekleme riskine karşı)
--    Şu an admin panelde bir sekmeye bağlı DEĞİL — istenirse SQL Editor'den
--    admin_token ile elle çağrılabilir, istenirse ileride panele de eklenir.
-- ------------------------------------------------------------
create or replace function public.admin_nk_ders_sil(p_admin_token text, p_id integer)
returns json
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then
        return json_build_object('basarili', false, 'hata', 'yetkisiz');
    end if;
    -- Soru içeren dersin silinmesini foreign key engeller.
    delete from public.nk_dersler where id = p_id;
    return json_build_object('basarili', true);
exception when foreign_key_violation or restrict_violation then
    return json_build_object('basarili', false, 'hata', 'Bu derste soru var; önce soruları taşıyın veya ayrı ayrı silin.');
end;
$function$;

create or replace function public.admin_nk_ders_duzenle(p_admin_token text, p_id integer, p_ders_adi text, p_ders_kodu text default null)
returns json
language plpgsql
security definer
set search_path to 'public', 'extensions'
as $function$
begin
    if not public._admin_token_gecerli_mi(p_admin_token) then
        return json_build_object('basarili', false, 'hata', 'yetkisiz');
    end if;
    update public.nk_dersler
    set ders_adi = trim(p_ders_adi), ders_kodu = nullif(trim(coalesce(p_ders_kodu, '')), '')
    where id = p_id;
    return json_build_object('basarili', true);
end;
$function$;

commit;
